(cl:defpackage my_custom_srv_msg_pkg-srv
  (:use )
  (:export
   "BB8CUSTOMSERVICEMESSAGE"
   "<BB8CUSTOMSERVICEMESSAGE-REQUEST>"
   "BB8CUSTOMSERVICEMESSAGE-REQUEST"
   "<BB8CUSTOMSERVICEMESSAGE-RESPONSE>"
   "BB8CUSTOMSERVICEMESSAGE-RESPONSE"
   "MYCUSTOMSERVICEMESSAGE"
   "<MYCUSTOMSERVICEMESSAGE-REQUEST>"
   "MYCUSTOMSERVICEMESSAGE-REQUEST"
   "<MYCUSTOMSERVICEMESSAGE-RESPONSE>"
   "MYCUSTOMSERVICEMESSAGE-RESPONSE"
  ))

