(cl:defpackage unit_5_services-srv
  (:use )
  (:export
   "BB8CUSTOMSERVICEMESSAGE"
   "<BB8CUSTOMSERVICEMESSAGE-REQUEST>"
   "BB8CUSTOMSERVICEMESSAGE-REQUEST"
   "<BB8CUSTOMSERVICEMESSAGE-RESPONSE>"
   "BB8CUSTOMSERVICEMESSAGE-RESPONSE"
  ))

