// Generated by gencpp from file my_custom_srv_msg_pkg/B88CustomServiceMessage.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_SRV_MSG_PKG_MESSAGE_B88CUSTOMSERVICEMESSAGE_H
#define MY_CUSTOM_SRV_MSG_PKG_MESSAGE_B88CUSTOMSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <my_custom_srv_msg_pkg/B88CustomServiceMessageRequest.h>
#include <my_custom_srv_msg_pkg/B88CustomServiceMessageResponse.h>


namespace my_custom_srv_msg_pkg
{

struct B88CustomServiceMessage
{

typedef B88CustomServiceMessageRequest Request;
typedef B88CustomServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct B88CustomServiceMessage
} // namespace my_custom_srv_msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessage > {
  static const char* value()
  {
    return "b78c0d1a37ffcec6adef7714dda05daa";
  }

  static const char* value(const ::my_custom_srv_msg_pkg::B88CustomServiceMessage&) { return value(); }
};

template<>
struct DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessage > {
  static const char* value()
  {
    return "my_custom_srv_msg_pkg/B88CustomServiceMessage";
  }

  static const char* value(const ::my_custom_srv_msg_pkg::B88CustomServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessageRequest> should match
// service_traits::MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >
template<>
struct MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >::value();
  }
  static const char* value(const ::my_custom_srv_msg_pkg::B88CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessageRequest> should match
// service_traits::DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >
template<>
struct DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >::value();
  }
  static const char* value(const ::my_custom_srv_msg_pkg::B88CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessageResponse> should match
// service_traits::MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >
template<>
struct MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >::value();
  }
  static const char* value(const ::my_custom_srv_msg_pkg::B88CustomServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessageResponse> should match
// service_traits::DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >
template<>
struct DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::my_custom_srv_msg_pkg::B88CustomServiceMessage >::value();
  }
  static const char* value(const ::my_custom_srv_msg_pkg::B88CustomServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_CUSTOM_SRV_MSG_PKG_MESSAGE_B88CUSTOMSERVICEMESSAGE_H
