(cl:defpackage my_python_class-srv
  (:use )
  (:export
   "MYCUSTOMSERVICEMESSAGE"
   "<MYCUSTOMSERVICEMESSAGE-REQUEST>"
   "MYCUSTOMSERVICEMESSAGE-REQUEST"
   "<MYCUSTOMSERVICEMESSAGE-RESPONSE>"
   "MYCUSTOMSERVICEMESSAGE-RESPONSE"
  ))

