// Generated by gencpp from file unit_5_services/BB8CustomServiceMessage.msg
// DO NOT EDIT!


#ifndef UNIT_5_SERVICES_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H
#define UNIT_5_SERVICES_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <unit_5_services/BB8CustomServiceMessageRequest.h>
#include <unit_5_services/BB8CustomServiceMessageResponse.h>


namespace unit_5_services
{

struct BB8CustomServiceMessage
{

typedef BB8CustomServiceMessageRequest Request;
typedef BB8CustomServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BB8CustomServiceMessage
} // namespace unit_5_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unit_5_services::BB8CustomServiceMessage > {
  static const char* value()
  {
    return "b78c0d1a37ffcec6adef7714dda05daa";
  }

  static const char* value(const ::unit_5_services::BB8CustomServiceMessage&) { return value(); }
};

template<>
struct DataType< ::unit_5_services::BB8CustomServiceMessage > {
  static const char* value()
  {
    return "unit_5_services/BB8CustomServiceMessage";
  }

  static const char* value(const ::unit_5_services::BB8CustomServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::unit_5_services::BB8CustomServiceMessageRequest> should match
// service_traits::MD5Sum< ::unit_5_services::BB8CustomServiceMessage >
template<>
struct MD5Sum< ::unit_5_services::BB8CustomServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unit_5_services::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::unit_5_services::BB8CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unit_5_services::BB8CustomServiceMessageRequest> should match
// service_traits::DataType< ::unit_5_services::BB8CustomServiceMessage >
template<>
struct DataType< ::unit_5_services::BB8CustomServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::unit_5_services::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::unit_5_services::BB8CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unit_5_services::BB8CustomServiceMessageResponse> should match
// service_traits::MD5Sum< ::unit_5_services::BB8CustomServiceMessage >
template<>
struct MD5Sum< ::unit_5_services::BB8CustomServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unit_5_services::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::unit_5_services::BB8CustomServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unit_5_services::BB8CustomServiceMessageResponse> should match
// service_traits::DataType< ::unit_5_services::BB8CustomServiceMessage >
template<>
struct DataType< ::unit_5_services::BB8CustomServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::unit_5_services::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::unit_5_services::BB8CustomServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNIT_5_SERVICES_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H
